import type {
  ActivityModule,
  ActivityRecord,
  NavigationItem,
  PrizeRecord,
  TaskRecord,
} from './types'

export const navigationItems: NavigationItem[] = [
  { id: 'overview', label: '工作台', icon: 'DataBoard' },
  { id: 'activities', label: '活动管理', icon: 'Calendar' },
  { id: 'editor', label: '页面编排', icon: 'SetUp', badge: '当前' },
  { id: 'tasks', label: '任务中心', icon: 'List' },
  { id: 'prizes', label: '奖品与奖池', icon: 'Present' },
  { id: 'assets', label: '素材中心', icon: 'Picture' },
  { id: 'publish', label: '发布审核', icon: 'Promotion', badge: '3' },
  { id: 'analytics', label: '数据看板', icon: 'TrendCharts' },
]

export const activities: ActivityRecord[] = [
  {
    id: 11025,
    name: 'PUBG 金秋双节补给行动',
    code: 'PUBG_AUTUMN_2026',
    template: '金秋小队模板',
    owner: '周沐',
    status: '进行中',
    device: 'PC + H5',
    startTime: '2026-09-25 00:00',
    endTime: '2026-10-11 23:59',
    updatedAt: '10 分钟前',
    modules: 5,
    users: '28.6 万',
  },
  {
    id: 11026,
    name: '国庆开黑季',
    code: 'NATIONAL_TEAM_UP',
    template: '社区盲盒模板',
    owner: '林栖',
    status: '待发布',
    device: 'PC + H5',
    startTime: '2026-09-28 00:00',
    endTime: '2026-10-11 23:59',
    updatedAt: '1 小时前',
    modules: 3,
    users: '--',
  },
  {
    id: 11021,
    name: '春野补给行动 V5',
    code: 'PUBG_SUPPLY_V5',
    template: '完整互动模板',
    owner: '陈屿',
    status: '已结束',
    device: 'PC + H5',
    startTime: '2026-06-18 12:00',
    endTime: '2026-07-08 23:59',
    updatedAt: '2026-07-09',
    modules: 6,
    users: '41.2 万',
  },
  {
    id: 11018,
    name: '春野补给行动 V4',
    code: 'PUBG_SUPPLY_V4',
    template: '经典补给模板',
    owner: '陈屿',
    status: '草稿',
    device: '仅 PC',
    startTime: '未设置',
    endTime: '未设置',
    updatedAt: '3 天前',
    modules: 6,
    users: '--',
  },
]

export const initialModules: ActivityModule[] = [
  {
    id: 'background',
    type: 'background',
    name: '页面背景',
    description: 'PC/H5 页面头图、分段背景和页尾背景素材',
    enabled: true,
    device: 'PC + H5',
  },
  {
    id: 'exchange',
    type: 'exchange',
    name: '积分兑换',
    description: '商品中心商品、积分价格、库存与限购规则',
    enabled: true,
    device: 'PC + H5',
  },
  {
    id: 'sign',
    type: 'sign',
    name: '每日签到',
    description: '周期签到、节日奖励与前置任务条件',
    enabled: true,
    device: 'PC + H5',
  },
  {
    id: 'task',
    type: 'task',
    name: '任务中心',
    description: '普通、每日、阶段、直播与游戏行为任务',
    enabled: true,
    device: 'PC + H5',
    warning: '2 个任务缺少跳转兜底文案',
  },
  {
    id: 'lottery',
    type: 'lottery',
    name: '福利抽奖',
    description: '普通/至臻双奖池，支持积分兑换抽奖次数',
    enabled: true,
    device: 'PC + H5',
  },
  {
    id: 'invite',
    type: 'invite',
    name: '小队任务',
    description: '短链入队、队员状态和四周小队累计任务',
    enabled: true,
    device: 'PC + H5',
  },
]

export const initialTasks: TaskRecord[] = [
  { id: 57, name: '每日抖音观赛', executor: '观看直播', cycle: '每日', target: 1, reward: '积分 ×100', condition: '登录', enabled: true },
  { id: 64, name: '绑定 PUBG 账号', executor: '账号绑定', cycle: '单次', target: 1, reward: '积分 ×200', condition: '登录', enabled: true },
  { id: 95, name: '每日击杀或助攻', executor: '游戏数据', cycle: '每日', target: 5, reward: '普通抽奖 ×1', condition: '已绑定', enabled: true },
  { id: 97, name: '每日成功吃鸡', executor: '游戏数据', cycle: '每日', target: 1, reward: '至臻抽奖 ×1', condition: '已绑定', enabled: true },
  { id: 98, name: '节日补给·载具移动', executor: '游戏数据', cycle: '活动累计', target: 10000, reward: '赛事票 ×2', condition: '节日时段', enabled: true },
  { id: 101, name: '邀请好友加入小队', executor: '邀请关系', cycle: '活动累计', target: 3, reward: '积分 ×500', condition: '已入队', enabled: true },
]

export const initialPrizes: PrizeRecord[] = [
  { id: 201, name: 'ROG 游戏手机', pool: '至臻奖池', type: '实物', probability: '0.0100%', stock: 3, limit: 1, status: '在架' },
  { id: 202, name: '京东卡 500 元', pool: '至臻奖池', type: 'CDK', probability: '0.0900%', stock: 20, limit: 1, status: '在架' },
  { id: 203, name: 'PUBG 稀有皮肤', pool: '普通奖池', type: '游戏道具', probability: '1.5000%', stock: 500, limit: 1, status: '在架' },
  { id: 204, name: 'NN 积分 100', pool: '普通奖池', type: '积分', probability: '28.4000%', stock: 999999, limit: 50, status: '在架' },
  { id: 205, name: '谢谢参与', pool: '普通奖池', type: '未中奖', probability: '70.0000%', stock: 999999, limit: 999, status: '在架' },
]
